train_set:
  type: CIFAR10
  root: ../dataset/CIFAR10
  division:
    method: iid
    long_tail: 0
    gamma_d: 0.774
    shuffle: 1
    gamma_c: 0.977
    tau: 2
  batch_size: 10
  transform:
    - ToTensor
    - Normalize:
        mean: [0.5, 0.5, 0.5]
        std: [0.5, 0.5, 0.5]

test_set:
  type: CIFAR10
  root: ../dataset/CIFAR10
  batch_size: 128
  transform:
    - ToTensor
    - Normalize:
        mean: [0.5, 0.5, 0.5]
        std: [0.5, 0.5, 0.5]
