_base_:
  - _base_/datasets/kinetics400_rgb_skeleton.yml
  - _base_/models/action_recognizer_posec3d_slowfast.yml

fl_method:
  type: Centralized
  epochs: 30

loss:
  type: BinaryCrossEntropyLoss

optimizer:
  type: AdamW
  betas: [0.9, 0.999]
  lr: 0.00005
  weight_decay: 0.05

model:
  pretrained: output/Centralized_Kinetics400RGBSkeleton_Recognizer3D_iid-0321/best_model/model.pth

# lr_scheduler:
#   type: MultiStepLR
#   milestones: [9, 11]
#   gamma: 0.1
lr_scheduler:
  type: CosineAnnealingWithWarmup
  T_warmup: 2.5
  T_max: 28
  eta_min: 0

