_base_:
  - _base_/datasets/ucf101_tiny_rgb_skeleton.yml
  - _base_/models/action_recognizer_posec3d_slowfast.yml

fl_method:
  type: AdaFed
  global_epoch: 200
  local_epoch: 3
  num_clients: 20
  frac: 0.25
  epsilon: 0.2

model:
  pretrained: ../pretrained/posec3d-400-20.pth

train_set:
  division:
    method: non-iid
    classes_per_client: 4

loss:
  type: BinaryCrossEntropyLoss

optimizer:
  type: AdamW
  betas: [0.9, 0.999]
  lr: 0.0001
  weight_decay: 0.05

lr_scheduler:
  type: CosineAnnealingWithWarmup
  T_warmup: 50
  T_max: 550
  eta_min: 0
