_base_:
  - _base_/datasets/ucf101_skeleton.yml
  - _base_/models/action_recognizer_posec3d_slowonly.yml

fl_method:
  type: Centralized
  epochs: 30

loss:
  type: CrossEntropyLoss

optimizer:
  type: AdamW
  betas: [0.9, 0.999]
  lr: 0.0005
  weight_decay: 0.05

# lr_scheduler:
#   type: MultiStepLR
#   milestones: [9, 11]
#   gamma: 0.1
lr_scheduler:
  type: CosineAnnealingLR
  T_max: 30
  eta_min: 0
