_base_:
  - _base_/datasets/ucf101_rgb_skeleton.yml
#  - _base_/datasets/ucf101_tiny_rgb_skeleton.yml
  - _base_/models/action_recognizer_posec3d_slowfast.yml

fl_method:
  type: Centralized
  epochs: 200

model:
  pretrained: ../pretrained/posec3d-400-20.pth

loss:
  type: BinaryCrossEntropyLoss

optimizer:
  type: AdamW
  betas: [0.9, 0.999]
  lr: 0.0005
  weight_decay: 0.05

# lr_scheduler:
#   type: MultiStepLR
#   milestones: [9, 11]
#   gamma: 0.1
lr_scheduler:
  type: CosineAnnealingWithWarmup
  T_warmup: 20
  T_max: 185
  eta_min: 0
