_base_:
  - _base_/datasets/ucf101.yml
#  - _base_/datasets/ucf101_tiny.yml
  - _base_/models/action_recognizer_swin_transformer.yml

fl_method:
  type: Centralized
  epochs: 32

loss:
  type: CrossEntropyLoss

optimizer:
  type: AdamW
  betas: [0.9, 0.999]
  lr: 0.00003
  weight_decay: 0.05

lr_scheduler:
  type: CosineAnnealingWithWarmup
  T_warmup: 2.5
  T_max: 30
  eta_min: 0
