_base_:
  - _base_/datasets/ucf101.yml
#  - _base_/datasets/ucf101_tiny.yml
  - _base_/models/action_recognizer_swin_transformer.yml

fl_method:
  type: FedAvg
  global_epoch: 200
  local_epoch: 3  # E
  num_clients: 20  # K
  frac: 0.25  # C
  local_bs: 2  # B

train_set:
  division:
    method: non-iid
    classes_per_client: 4

loss:
  type: CrossEntropyLoss

optimizer:
  type: AdamW
  betas: [0.9, 0.999]
  lr: 0.00003
  weight_decay: 0.05

lr_scheduler:
  type: CosineAnnealingWithWarmup
  T_warmup: 50
  T_max: 550  # global_epoch * local_epoch
  eta_min: 0
