_base_:
  - _base_/datasets/mnist.yml

fl_method:
  type: Centralized
  epochs: 30

model:
 type: CNNMnist
#  in_channels: 1
#  num_classes: 10

# model:
#  type: MLPImage
#  in_dim: 784
#  hidden_dim: 100
#  out_dim: 10

# model:
#   type: ResNet18Cifar

loss:
  type: CrossEntropyLoss

optimizer:
  type: SGD
  lr: 0.01
  momentum: 0.5
  weight_decay: 0.0001

lr_scheduler:
  type: StepLR
  step_size: 10
  gamma: 0.3
