_base_:
  - _base_/datasets/mnist.yml

fl_method:
  type: MOON
  global_epoch: 100
  local_epoch: 10
  num_clients: 100
  frac: 0.1
  temperature: 0.5
  miu: 0.01

train_set:
  batch_size: 10
  division:
    method: iid

model:
  type: CNNMnistMOON

loss:
  type: CrossEntropyLoss

optimizer:
  type: SGD
  lr: 0.01
  momentum: 0.9
#  weight_decay: 0.0001

#lr_scheduler:
#  type: StepLR
#  step_size: 20
#  gamma: 0.3
