model:
  type: Recognizer3D
  backbone:
    type: SwinTransformer3D
    pretrained: ../pretrained/swin_base_patch4_window7_224.pth
    input_format: NCDHW  # NCDHW or NDHWC
    patch_size: [2, 4, 4]
    embed_dim: 128
    depths: [2, 2, 18, 2]
    num_heads: [4, 8, 16, 32]
    window_size: [8, 7, 7]
    mlp_ratio: 4.
    qkv_bias: True
    drop_rate: 0.0
    attn_drop_rate: 0.0
    drop_path_rate: 0.2
    patch_norm: True
  head:
    type: I3DHead
    in_channels: 1024
